In [26]:
import pandas as pd 
import re
import numpy as np

In [27]:
mbenz_df = pd.read_csv("../../datasets/processed/mdz_cleaned.v2.csv")     # load the benz clean data 
semienz_df = pd.read_csv("../../datasets/processed/semienz_cleaned.v2.csv")  # load the semiez prepareed data

In [7]:
semienz_df.head()

,Unnamed: 0,job_id,job_title,posted_since,organization,field_of_work,company,experience_level,job_type,work_mode,employment_type,location,new_description,clean_description,final_job_description
0,0,503010,Service Architect for network services,2026-05-05,Information Technology,Information Technology,Siemens Technology and Services Private Limited,Experienced Professional,Full-time,Office/Site only,Permanent,Bangalore - Karnataka - India,"Hello Visionary,\nWe empower our people to sta...","Hello Visionary,\nWe empower our people to sta...",hello visionary we empower our people to stay ...
1,1,503299,"Werkstudent (w/m/d) Marketing, Communication &...",2026-05-05,Global Business Services,Internal Services,Siemens AG,Student (Not Yet Graduated),Part-time,Office/Site only,Fixed Term,Mannheim - Baden-Wuerttemberg - Germany,Become part of our team as a working student (...,Become part of our team as a working student (...,become part of our team as a working student f...
2,2,503374,Site Reliability Engineer,2026-05-05,Foundational Technologies,Research & Development,Siemens Technology and Services Private Limited,Experienced Professional,Full-time,Office/Site only,Permanent,Bangalore - Karnataka - India,We empower our people to stay resilient and re...,We empower our people to stay resilient and re...,we empower our people to stay resilient and re...
3,8,503133,Data Scientist & Data Product Manager in MR (f...,2026-05-06,Siemens Healthineers,Research & Development,Siemens Healthineers AG,Mid-level Professional,Full-time/Part-time,Hybrid (Remote/Office),Permanent,Erlangen - - Germany,"Our name, Siemens Healthineers, was selected t...","Our name, Siemens Healthineers, was selected t...",our name siemens healthineers was selected to ...
4,9,503134,Data Strategist & Data Architect in MR (f/m/d),2026-05-06,Siemens Healthineers,Research & Development,Siemens Healthineers AG,Experienced Professional,Full-time/Part-time,Hybrid (Remote/Office),Permanent,Erlangen - - Germany,"Our name, Siemens Healthineers, was selected t...","Our name, Siemens Healthineers, was selected t...",our name siemens healthineers was selected to ...

In [30]:
mbenz_df.clean_description.to_list()[10:14]

["mercedes-benz ag is responsible for the global business of mercedes-benz cars and mercedes-benz vans worldwide. the company's focus is on the development, production and sales of cars and vans as well as services. are you a pupil or student or are you in the transition period between school and studies/training, are you motivated and would you like to support us? then you have come to the right place with us as part of a holiday job and we look forward to receiving your application. to work at the mercedes-benz plant in bremen, we are looking for holiday employees (f/m/d) in the area of \u200b\u200bproduction and logistics with, among other things, the following tasks: assembly work, she will construction work, working in the press shop, driving a forklift. depending on the tariff area within the location, you will have a weekly working time of 35/38/39 hours you are attending school or studying or are in the transition period between school and studies/training/secondary school or federal voluntary service/voluntary military service. you are already 18 years old, have a good knowledge of german and are able to work for at least 4 weeks in the period from may 25th, 2026 to august 29th, 2026. we are preferably looking for holiday employees for 4 weeks or longer for the period from june 22nd, 2026. additional information the job is full-time, limited to 24 week(s) in shift work. find out more in advance of your employment additional earnings limits and social security obligations in the context of child benefit claims and bafög. please understand that the processing of your application may take some time and remember that the planning can also take place at very short notice due to updates in the requirements planning. please only apply online. please check your email inbox and spam folder regularly for further information about your application. we particularly welcome online applications from do you have questions? you can find answers and further contact options in our faq. you can also use our chat function to receive further information. we look forward to receiving your application!",
 "visual inspection of the bodywork, recognition of defects and quality deficiencies replacement of doors, bonnet, tailgate and proper adjustment of gap dimensions preparation and provision of workpieces and raw materials completed qualification in bodywork (or relevant related qualifications: welder, machine cutter, cnc, mechanical engineering technician, structural locksmith); relevant professional experience is an advantage multi-shift work schedule accurate and responsible work, commitment to quality team spirit, flexibility native-level hungarian language skills in speech and writing why is it worth working at the mercedes-benz factory in kecskemét?: *competitive base salary complex benefits package (attendance bonus, seniority bonus, vacation allowance, 13th month salary, travel allowance - 100% support in the case of public transport) direct bus routes from kecskemét and its catchment area settlement support supportive atmosphere, people-oriented management and cohesive team vibrant, stable, international environment professional training, development and advancement opportunities daily use of german and/or english employee discounts with ouresearch and developmentesignated partners collective life and accident insurance sports opportunities (kecskemét fürdő, kecskemét and gyms around kecskemét) meals available in all factory departments for colleagues wide selection of modern, comfortable work clothes health-preserving measures (company psychologist, health month: flu vaccination, health education, prevention lectures) implementation of innovative and creative ideas is recognized and rewarded * the items listed above can be used according to the conditions specified in the employer's regulations. a stable workplace, professional development and an outstanding benefits package - these are guaranteed by the mercedes-benz factory in kecskemét. use your knowledge and professional experience with us and join our constantly expanding team! if you are interested in our ad, register in our candidate database and upload your professional resume!",
 "mercedes-benz ag is responsible for the global business of mercedes-benz cars and mercedes-benz vans worldwide. the company's focus is on the development, production and sales of cars and vans as well as services. are you a pupil or student or are you in the transition period between school and studies/training, are you motivated and would you like to support us? then you have come to the right place with us for holiday employment and we look forward to receiving your application. to work at the mercedes-benz germersheim plant, we are looking for holiday employees (f/m/d) for the germersheim and offenbach an der queich plant parts in the area of logistics and technical factory service with, among other things, the following tasks: forklift driving, storage, packing, order picking, warehouse management and inventory maintenance. they will be deployed in two shifts (early and late shifts on a weekly basis change). depending on the tariff area within the location, you have a weekly working time of 39 hours you are attending school or studying or are in the transition period between school and studies/training/secondary school or federal voluntary service/voluntary military service. you are already 18 years old, have good knowledge of german and are able to work for at least 4 weeks in the period from june 29th, 2026 to november 28th, 2026. additional information the job is full-time, limited to 24 weeks in shift work. in advance of your employment, find out about additional earnings limits and social security obligations in the context of child benefit claims and bafög. please understand that the processing of your applying can take some time and please remember that planning can also take place at very short notice due to updates in requirements planning. please check your email inbox and spam folder regularly for further information about your application. we particularly welcome online applications from do you have questions? you can find answers and further contact options in our faq. you can also use our chat function to receive further information. we look forward to receiving your application!",
 'take a look beneath the surface you are fascinated by our cars, especially by their bodies and surfaces in a wide variety of shapes and coating processes. then in this training you will learn a wide variety of surface processing and painting techniques. your tasks application of pretreatment processes, as well as application technology and system technology coating vehicle bodies operation and monitoring of modern painting systems and spray robots technical understanding and technical talentgood knowledge of mathematics, chemistry and physicsgood spatial imaginationgood color visiona sense of responsibility, care and precise way of workingadditional information:for your application you should have at least a good secondary school leaving certificate or a secondary school leaving certificate. if you start with us, you can expect an attractive salary ranging from 1, 332 euros in the first year of training to 1, 434 euros in the final year (depending on location). if you successfully complete your training, you will have the best chance of being employed with us.']

In [ ]:
semienz_df.new_description.to_list()[10]

# Rename and Extract important columns

In [9]:
mbenz_df.rename(columns={
    "job_category" : "field_of_work",
    "working_mode" : "job_type", 
    "organization" : "company", 
    "publication"  : "posted_since"
},inplace=True)

semienz_df.rename(columns={
    "organization" : "Department",
    "clean_description" : "level1_clean",
    "final_job_description" : "clean_description",
    "job_title" : "title"
},inplace=True)

In [10]:
mbz_df = mbenz_df[["job_id","title","field_of_work","posted_since","company","Department","job_type","location","clean_description"]].copy()
smnz_df = semienz_df[["job_id","title","field_of_work","posted_since","company","Department","job_type","location","clean_description"]].copy()

In [11]:
mbz_df.head()

,job_id,title,field_of_work,posted_since,company,Department,job_type,location,clean_description
0,MER000441Q,"Manager, Public Relations",Others,15.06.2026,Mercedes-Benz Malaysia Sdn. Bhd.,SEA Marketing & Digital,Full time,"Mercedes-Benz Malaysia Sdn. Bhd., Kuala Lumpur","objective of job develop, plan, and execute mb..."
1,MER0003T59,"Assistant Manager, Tax Specialist",Finance/Controlling,15.06.2026,Mercedes-Benz Malaysia Sdn. Bhd.,Finance & Controlling MBPLAP,Full time,"Mercedes-Benz Malaysia Sdn. Bhd., Kuala Lumpur",objective of jobresponsible for managing organ...
2,MER00044DU,Process Engineer – Automation & Controls,Production,15.06.2026,Mercedes-Benz Manufacturing Poland sp. z o. o.,Engineering,Full time,Mercedes-Benz Manufacturing Poland sp. z o. o....,"looking for new challenges? the term ""automati..."
3,MER00044DN,Full Stack Developer - HUD Miner,Research and Development incl. Design,15.06.2026,Mercedes-Benz Research and Development India P...,Production Planning 1,Full time,Mercedes-Benz Research and Development India P...,about mbrdi:mercedes-benz research and develop...
4,MER0003ZHY,C# .NET Developer,Research and Development incl. Design,15.06.2026,Mercedes-Benz Research and Development India P...,Central Data Products,Full time,Mercedes-Benz Research and Development India P...,net developer (c#)experience: +5 yearsoverview...

## Change the type of posted_since column to Datetime format

In [12]:
mbz_df['posted_since'] = pd.to_datetime(mbz_df['posted_since'],format='mixed')
smnz_df['posted_since'] = pd.to_datetime(smnz_df['posted_since'], format='mixed')

## Combined benz and Semiens Job applications data

In [13]:
integrated_df = pd.concat([mbz_df,smnz_df])

In [14]:
integrated_df.shape

(2923, 9)

In [15]:
pd.unique(integrated_df.job_type)

<ArrowStringArray>
[                     'Full time', 'Full time (part time possible)',
                      'Part time',                      'Full-time',
                      'Part-time',            'Full-time/Part-time',
            'Full-Time temporary',            'Part-time temporary']
Length: 8, dtype: str

In [13]:
pd.unique(integrated_df.title)

<ArrowStringArray>
[                                                            'Manager, Public Relations',
                                                     'Assistant Manager, Tax Specialist',
                                              'Process Engineer – Automation & Controls',
                                                      'Full Stack Developer - HUD Miner',
                                                                     'C# .NET Developer',
                                                                'Digital Twin Developer',
                                            'Full Stack Developer JAVA_REACT_Vue_Kotlin',
                                        'Full Stack Developer JAVA_REACT_Vue_Kotlin _ 2',
            'Entwicklungsingenieur*in – Software- & Funktionsentwicklung Klimatisierung',
 'KFZ-Mechatroniker(w/m/d) für Transporter in der Mercedes-Benz Niederlassung Frankfurt',
 ...
                                                          'Lead – Materials & Logistics',
                                                 'Order Manager - Dutch Speaker (m/f/d)',
                                                                   'Solar PV Instructor',
                  'Floor Assembly Technician - Products & Machines (Production Chemist)',
                                     'Werkstudent (w/m/d) Business Development Vertrieb',
                                    'System Engineer - Scada / Control Relay Protection',
                                                 'Mitarbeiter*in Änderungswesen (w/m/d)',
                                       'Werkstudent (w/m/d) Produktportfolio-Management',
                    'Product Manager for Cross-Segment & Cross-Portfolio Topics (m/f/d)',
                                                     'Strategic Product Manager (m/f/d)']
Length: 2674, dtype: str

# Translate the Language at title level

In [16]:
from langdetect import detect
from deep_translator import GoogleTranslator

def translate_to_english(text):
    try:
        lang = detect(text)

        if lang == "en":
            return text

        translated = GoogleTranslator(source=lang, target="en").translate(text)
        return translated

    except:
        return text  # fallback if detection fails

In [17]:
integrated_df.title = integrated_df.title.apply(translate_to_english)

In [20]:
integrated_df.title.to_list()[:30]

['Manager, Public Relations',
 'Assistant Manager, Tax Specialist',
 'Process Engineer – Automation & Controls',
 'Full Stack Developer - HUD Miner',
 'C# .NET Developer',
 'Digital Twin Developer',
 'Full Stack Developer JAVA_REACT_Vue_Kotlin',
 'Full Stack Developer JAVA_REACT_Vue_Kotlin _ 2',
 'Development engineer – software and functional development for air conditioning',
 'Automotive mechatronics technician (f/m/d) for vans in the Mercedes-Benz Frankfurt branch',
 'Holiday job in the production plant in Bremen summer 2026',
 'Sheet metal worker',
 'Holiday job at the Global Logistics Center Germersheim summer 2026',
 'Training as a process mechanic (f/m/d) for coating technology, Mercedes-Benz AG, Bremen plant, training begins September 1st, 2026',
 'Battery Mechanical System Engineer',
 'Remote Monitoring System Development Engineer',
 'Intern supporting press test car engineering',
 'Intern External and Internal Communication with a focus on public relations',
 'Intern Digital Process Innovation',
 'Intern Marketing & Sales / Project Management, Volume & Pricing VAN.EA (mandatory internship)',
 'Working student AI training for design systems',
 'Facility Intern',
 'IT Intern - MYMI 2026',
 'Practical Arbeitspolitik',
 'Working student AI & process optimization in the IT environment',
 'Intern project management battery production (mandatory internship)',
 'Warehouse logistics specialist (f/m/d) at the Mercedes-Benz Frankfurt branch',
 'Intern Software Development for Electric Drives',
 'Full stack with java microservices with AI skills',
 'Full Stack Developer']

In [18]:
len(mbz_df)

1020

In [ ]:
integrated_df.clean_description.to_list()

# Standarized the JOb type value

In [22]:
def clean_employment_type(text):
    text = text.lower()

    # Replace separators with spaces
    text = text.replace('-', ' ')
    return text

integrated_df.job_type = integrated_df.job_type.apply(clean_employment_type)

In [20]:
#integrated_df.to_csv("../../datasets/processed/stage1_integrated.csv")

# Reconstruct a complete job description following the required format

In [23]:

def build_embedding_text(row):
    return f"""
            Job Title: {row['title']}
            Company: {row['company']}
            Department : {row["Department"]}

            
            Job Details:
            - Job Type: {row['job_type']}
            - Posted since : {row["posted_since"]}
            - Domain: {row['field_of_work']}
            - Location: {row['location']}
            
            Responsibilities & Requirements:
            {row['clean_description']}
        """.strip()
    
integrated_df["description_improved"] = integrated_df[
    [
        'title', 'field_of_work', 'company',
        'job_type','Department',"posted_since",
        'location', 'clean_description'
    ]
].apply(build_embedding_text, axis=1)

In [24]:
integrated_df.head(3)

,job_id,title,field_of_work,posted_since,company,Department,job_type,location,clean_description,description_improved
0,MER000441Q,"Manager, Public Relations",Others,2026-06-15,Mercedes-Benz Malaysia Sdn. Bhd.,SEA Marketing & Digital,full time,"Mercedes-Benz Malaysia Sdn. Bhd., Kuala Lumpur","objective of job develop, plan, and execute mb...","Job Title: Manager, Public Relations\n ..."
1,MER0003T59,"Assistant Manager, Tax Specialist",Finance/Controlling,2026-06-15,Mercedes-Benz Malaysia Sdn. Bhd.,Finance & Controlling MBPLAP,full time,"Mercedes-Benz Malaysia Sdn. Bhd., Kuala Lumpur",objective of jobresponsible for managing organ...,"Job Title: Assistant Manager, Tax Specialist\n..."
2,MER00044DU,Process Engineer – Automation & Controls,Production,2026-06-15,Mercedes-Benz Manufacturing Poland sp. z o. o.,Engineering,full time,Mercedes-Benz Manufacturing Poland sp. z o. o....,"looking for new challenges? the term ""automati...",Job Title: Process Engineer – Automation & Con...

In [25]:
integrated_df.to_csv("../../datasets/processed/integrated_dataset.v2.csv",index=False)